site_name: canonical-imports
site_url: https://15r10nk.github.io/canonical-imports/
repo_url: https://github.com/15r10nk/canonical-imports/
edit_uri: edit/main/docs

theme:
  name: material
  features:
  - toc.follow
  palette:
    primary: teal

watch:
- CONTRIBUTING.md
- CHANGELOG.md
- README.md

nav:
- Introduction: index.md
- Contributing: contributing.md
- Changelog: changelog.md


markdown_extensions:
- toc:
    permalink: true
- admonition
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_source: false
- social
- search

extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://x.com/15r10nk
